install.packages('data.table')
install.packages('Rtsne')
install.packages('ggplot2')
install.packages('caret')
install.packages('ClusterR')

library(data.table)
library(Rtsne)
library(ggplot2)
library(caret)
library(ClusterR)
